/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interbloqueo.java
 *
 * Created on 8/06/2010, 02:12:38 PM
 */

package proyectointerbloqueos;

import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SEVEN
 */
public class Interbloqueo extends javax.swing.JFrame {

   
    static int cont;
    public static Vector p,r;
    public static Random ran;
    private Thread hilo;


    /** Creates new form Interbloqueo */
    public Interbloqueo() {
        initComponents();

                p=new Vector();
		r=new Vector();
		ran=new Random();
		Thread hilo;

		Recurso r0=new Recurso();
		r0.setNombre("r0");
		r0.setOcupado(false);
		r0.setTipo("EX");

		Recurso r1=new Recurso();
		r1.setNombre("r1");
		r1.setOcupado(false);
		r1.setTipo("NOEX");

		Recurso r2=new Recurso();
		r2.setNombre("r2");
		r2.setOcupado(false);
		r2.setTipo("EX");

		Recurso r3=new Recurso();
		r3.setNombre("r3");
		r3.setOcupado(false);
		r3.setTipo("NOEX");

		Recurso r4=new Recurso();
		r4.setNombre("r4");
		r4.setOcupado(false);
		r4.setTipo("EX");

		Recurso r5=new Recurso();
		r5.setNombre("r5");
		r5.setOcupado(false);
		r5.setTipo("NOEX");

		r.add(r0);
		r.add(r1);
		r.add(r2);
		r.add(r3);
		r.add(r4);
		r.add(r5);

		while(cont<6){
			p.add(new Procesos());
			cont++;
		}




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Recursos");

        jLabel2.setText("Procesos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


            new Thread(){

                public void run(){

                    iniciarInterbloqueo();
                }

            }.start();

            jButton1.setEnabled(false);




    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interbloqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables


    public void iniciarInterbloqueo(){

        		while(true){
            try {
                //Se escoge el recurso n
                int n = ran.nextInt(6);
                System.out.println("/////////////////////////////////////////////////");
                System.out.println("se escogio recurso" + n);
                jTextArea1.append(" Recurso " + n + "\n");

                System.out.println("/////////////////////////////////////////////////");
                Procesos pro;
                Recurso rec = (Recurso) r.get(n);
                if ((rec.getTipo().equals("EX")) || (rec.getTipo().equals("NOEX") && (rec.isOcupado() == false))) //if( rec.getTipo().equals("EX"))
                {
                    boolean encuentraProceso = false;
                    int i = 0;
                    while (!encuentraProceso) {
                        if (i == p.size()) {
                            i = 0;
                        }
                        pro = (Procesos) p.get(i);
                        if (!pro.isTieneRecurso()) {
                            Recurso rn = (Recurso) r.get(n);
                            //pro.setRecurso((Recurso) r.get(n));
                            pro.setRecurso(rn);
                            rn.setOcupado(true);
                            System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
                            System.out.println("inicio proceso " + i + " con recurso " + n);
                            jTextArea2.append(" Recurso " + n + " en Proceso " + i+"\n");


                            System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&");
                            hilo = new Thread(pro);
                            hilo.start();
                            encuentraProceso = true;
                        }
                        i++;
                    }
                }
                Random ra = new Random();
                int e = ra.nextInt(5) + 1;
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Interbloqueo.class.getName()).log(Level.SEVERE, null, ex);
            }

	}



    }

}
